### ISSUE TITLE
groupBy implementation

### ISSUE THREAD

**Issue by rhyek** [logaretm/collectionsjs#1]
Hi! Great library. Javascript has come a long way recently, but there's just a few Array methods missing when compared to something like Laravel's Collections or .Net's LINQ, so good job!

Anyways, any plans on implementing `groupBy`?

**Comment by logaretm** [comment]
Thanks, but currently I'm overwhelmed by other projects, I suggest taking a look at the more mature [collect.js](https://github.com/ecrmnn/collect.js) which probably got you covered and very well maintained.

I kind of plan to move in another direction with this package, towards lazy collections which behave more like LINQ where the enumerable pipeline does not execute until the value is evaluated which should be very useful for huge collections.

**Comment by rhyek** [comment]
Thank you.
